apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ userID }}-tls
  namespace: "{{ userID }}"
spec:
  secretName: {{ userID }}-com-tls
  issuerRef:
    name: letsencrypt-{{ userID }}
  dnsNames:
  - {{ userDomain }}