apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ userID }}
  namespace: "{{ userID }}"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ email }}
    privateKeySecretRef:
      name: letsencrypt-{{ userID }}
    solvers:
    - selector: {}
      http01:
        ingress:
          ingressClassName: webapprouting.kubernetes.azure.com