apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ userID }}"
  namespace: "{{ userID }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust this based on your storage requirements