apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ userID }}"
  name: service-{{ userID }}
  namespace: "{{ userID }}"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "{{ userID }}"
  type: ClusterIP
status:
  loadBalancer: {}
